//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCompromised
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ReportedInfo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
