//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public bool Gender { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string MaidenName { get; set; }
        public Nullable<int> SSN { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public int EthnicityHispanicBinID { get; set; }
        public Nullable<int> ProgramBinID { get; set; }
        public Nullable<int> InsuranceBinID { get; set; }
        public Nullable<int> MedicareBinID { get; set; }
        public Nullable<int> ReminderBinID { get; set; }
        public string ChartNumber { get; set; }
        public bool LegalPresence { get; set; }
        public bool IncomeEligible { get; set; }
        public bool InsuranceEligible { get; set; }
        public Nullable<int> MonthlyIncome { get; set; }
        public Nullable<int> NumberLivingOnIncome { get; set; }
        public Nullable<decimal> PercentPoverty { get; set; }
        public Nullable<int> HeardOfProgramBinID { get; set; }
        public Nullable<int> ActiveBinID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public string Tribe { get; set; }
        public string Other { get; set; }
        public string Street { get; set; }
        public Nullable<int> CityBinID { get; set; }
        public int StateBinID { get; set; }
        public int ZipCode { get; set; }
        public int CountyBinID { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> PhoneBinID { get; set; }
        public string PhoneNumber { get; set; }
        public string EmergencyName { get; set; }
        public bool FPL { get; set; }
        public Nullable<int> TobaccoUseBinID { get; set; }
        public Nullable<int> Race_RaceID { get; set; }
        public Nullable<int> EducationBinID { get; set; }
        public Nullable<int> LanguageBinID { get; set; }
        public Nullable<int> UninsuredClientReferredBinID { get; set; }
    }
}
