//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalCycle
    {
        public int ClinicalCycleID { get; set; }
        public Nullable<long> OfficeVisitGuidID { get; set; }
        public int ClientID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string UserName { get; set; }
        public int SiteID { get; set; }
        public string Comments { get; set; }
        public System.DateTime ClinicalCycleDate { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public bool Pending { get; set; }
        public Nullable<int> ScreeningMethodBinID { get; set; }
        public Nullable<int> LegacyID { get; set; }
    }
}
