//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public Nullable<int> AgencySiteID { get; set; }
        public string RoutingNumber { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<System.DateTime> DateFYStart { get; set; }
        public Nullable<System.DateTime> DateFYEnd { get; set; }
        public string ObjectCode { get; set; }
        public int TypeID { get; set; }
        public Nullable<decimal> RateState { get; set; }
        public Nullable<decimal> RateFederal { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
