//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public Nullable<int> AgencySiteID { get; set; }
        public string AgencySiteName { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneExtension { get; set; }
        public Nullable<long> Fax { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
