//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_ClinicVisitTypes
    {
        public int ID { get; set; }
        public string Program { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string CPTCode { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> System { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Type { get; set; }
        public string TertiaryType { get; set; }
    }
}
