//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_ProcedureRate
    {
        public int ID { get; set; }
        public Nullable<int> ProcedureMethodBinID { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CPTCodeUsed { get; set; }
    }
}
