//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeIdentified_Person_2015
    {
        public int Person_ID { get; set; }
        public string Ethnicity { get; set; }
        public string Race { get; set; }
        public string Person_Sex_Cd { get; set; }
        public string County { get; set; }
        public string SSN { get; set; }
        public string Insurance { get; set; }
        public string Insurance_Sub_Type { get; set; }
        public string Primary_Language { get; set; }
        public string Limited_English { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<int> NumberinFamily { get; set; }
    }
}
