//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delete_History
    {
        public int DHID { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string DeletedBy { get; set; }
        public System.DateTime DateDeleted { get; set; }
    }
}
