//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDownload
    {
        public int ID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Program { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public string FileType { get; set; }
        public string FileExtension { get; set; }
        public Nullable<System.DateTime> DateFile { get; set; }
        public Nullable<int> Usage { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Updatedby { get; set; }
    }
}
