//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eCaSTContextEntities : DbContext
    {
        public eCaSTContextEntities()
            : base("name=eCaSTContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClinicalCycle> ClinicalCycles { get; set; }
        public virtual DbSet<DDCancerTypeBin> DDCancerTypeBins { get; set; }
        public virtual DbSet<Screening> Screenings { get; set; }
    }
}
