//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int EID { get; set; }
        public string ClinicID { get; set; }
        public string PatientLinkID { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> DateFileCreated { get; set; }
        public bool ErrClinicID { get; set; }
        public bool ErrPatientLinkID { get; set; }
        public bool ErrDateVisit { get; set; }
        public bool LastName { get; set; }
        public bool FirstName { get; set; }
        public bool MailingAddressCity { get; set; }
        public bool MailingAddressState { get; set; }
        public bool MailingAddressCounty { get; set; }
        public bool MailingAddressZip { get; set; }
        public bool DateOfBirth { get; set; }
        public bool Sex { get; set; }
        public bool HasSSN { get; set; }
        public bool Race { get; set; }
        public bool Ethnicity { get; set; }
        public bool PrimaryLanguage { get; set; }
        public bool NumberInFamily { get; set; }
        public bool PrimaryProvider { get; set; }
        public bool ConMethodBeforeVisit { get; set; }
        public bool ConMethodAfterVisit { get; set; }
        public bool Procedures { get; set; }
        public bool ErrDateFileCreated { get; set; }
        public bool LimitedEnglishIndicator { get; set; }
        public bool Insurance { get; set; }
        public bool InsuranceAdditional { get; set; }
        public bool PrimaryVisitType { get; set; }
        public bool Income { get; set; }
        public bool IncomePeriod { get; set; }
        public System.DateTime DateUpdated { get; set; }
    }
}
