//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extract_Correction
    {
        public int ID { get; set; }
        public string PatLinkID { get; set; }
        public string VisitDate { get; set; }
        public string PrimaryLanguage { get; set; }
        public string LimitedEnglish { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
    }
}
