//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extract2_Correction
    {
        public int ID { get; set; }
        public string PatLinkID { get; set; }
        public string VisitDate { get; set; }
        public string Procedure01 { get; set; }
        public string Procedure02 { get; set; }
        public string Procedure03 { get; set; }
        public string Procedure04 { get; set; }
        public string Procedure05 { get; set; }
        public string Procedure06 { get; set; }
        public string Procedure07 { get; set; }
        public string Procedure08 { get; set; }
        public string Procedure09 { get; set; }
        public string Procedure10 { get; set; }
        public string Procedure11 { get; set; }
        public string Procedure12 { get; set; }
        public string Procedure13 { get; set; }
        public string Procedure14 { get; set; }
        public string Procedure15 { get; set; }
        public string Procedure16 { get; set; }
        public string Procedure17 { get; set; }
        public string Procedure18 { get; set; }
        public string Procedure19 { get; set; }
        public string Procedure20 { get; set; }
    }
}
