//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergeCas
    {
        public int ID { get; set; }
        public Nullable<int> KPersonID { get; set; }
        public Nullable<int> DPersonID { get; set; }
        public Nullable<System.DateTime> DateMerge { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> RecordID { get; set; }
    }
}
