//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MarriageEntities : DbContext
    {
        public MarriageEntities()
            : base("name=MarriageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DD_AgencyFunction> DD_AgencyFunction { get; set; }
        public virtual DbSet<DD_AgencyType> DD_AgencyType { get; set; }
        public virtual DbSet<DD_Counties> DD_Counties { get; set; }
        public virtual DbSet<DD_DisolutionDecreeType> DD_DisolutionDecreeType { get; set; }
        public virtual DbSet<DD_MaritalCeremonyType> DD_MaritalCeremonyType { get; set; }
        public virtual DbSet<DD_MaritalPartiesRelated> DD_MaritalPartiesRelated { get; set; }
        public virtual DbSet<DD_MaritalRecordType> DD_MaritalRecordType { get; set; }
        public virtual DbSet<DD_MaritalStatus> DD_MaritalStatus { get; set; }
        public virtual DbSet<DD_States> DD_States { get; set; }
        public virtual DbSet<tblDissolutionAudit> tblDissolutionAudits { get; set; }
        public virtual DbSet<tblDissolutionData> tblDissolutionDatas { get; set; }
        public virtual DbSet<tblMarriageAudit> tblMarriageAudits { get; set; }
        public virtual DbSet<tblMarriageData> tblMarriageDatas { get; set; }
        public virtual DbSet<tblMarriageFileUploadData> tblMarriageFileUploadDatas { get; set; }
        public virtual DbSet<tblMarriageFileUpload> tblMarriageFileUploads { get; set; }
        public virtual DbSet<tblMarriageFTPFilesToProcess> tblMarriageFTPFilesToProcesses { get; set; }
        public virtual DbSet<tblMarriagePrintLog> tblMarriagePrintLogs { get; set; }
        public virtual DbSet<tblMarriageSearchLog> tblMarriageSearchLogs { get; set; }
        public virtual DbSet<tblUserAccount> tblUserAccounts { get; set; }
        public virtual DbSet<tblUserCountyAccess> tblUserCountyAccesses { get; set; }
        public virtual DbSet<tblUserPermission> tblUserPermissions { get; set; }
    
        public virtual ObjectResult<App_DropDown_Result> App_DropDown(string table, string orderBy, string programCode)
        {
            var tableParameter = table != null ?
                new ObjectParameter("Table", table) :
                new ObjectParameter("Table", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var programCodeParameter = programCode != null ?
                new ObjectParameter("ProgramCode", programCode) :
                new ObjectParameter("ProgramCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<App_DropDown_Result>("App_DropDown", tableParameter, orderByParameter, programCodeParameter);
        }
    
        public virtual int App_ReturnDropDown(string table, string orderBy, string programCode)
        {
            var tableParameter = table != null ?
                new ObjectParameter("Table", table) :
                new ObjectParameter("Table", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var programCodeParameter = programCode != null ?
                new ObjectParameter("ProgramCode", programCode) :
                new ObjectParameter("ProgramCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("App_ReturnDropDown", tableParameter, orderByParameter, programCodeParameter);
        }
    
        public virtual ObjectResult<GetCertificateData_Result> GetCertificateData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCertificateData_Result>("GetCertificateData");
        }
    
        public virtual ObjectResult<GetCertificateDataP_Result> GetCertificateDataP(string mrgID)
        {
            var mrgIDParameter = mrgID != null ?
                new ObjectParameter("MrgID", mrgID) :
                new ObjectParameter("MrgID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCertificateDataP_Result>("GetCertificateDataP", mrgIDParameter);
        }
    }
}
