//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_DD_TransactionDirections
    {
        public int TransactionDirectionID { get; set; }
        public string TransactionDirectionCode { get; set; }
        public string TransactionDirectionDescription { get; set; }
    }
}
