//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_Communication
    {
        public int NCID { get; set; }
        public string Program { get; set; }
        public Nullable<System.DateTime> DateOBPrepared { get; set; }
        public Nullable<System.DateTime> DateOBtoFile { get; set; }
        public Nullable<System.DateTime> DateIBProcess { get; set; }
        public string FileSourceName { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    }
}
