//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int TransactionDirectionID { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
        public Nullable<int> AuthorizationCodeID { get; set; }
        public int DestinationNESTProgramID { get; set; }
        public int OriginNESTProgramID { get; set; }
        public string DestinationPID { get; set; }
        public string OriginPID { get; set; }
        public string NESTPID { get; set; }
        public string EBCNumber { get; set; }
        public string SSN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> NameSuffixID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string AKALastName { get; set; }
        public string AKAFirstName { get; set; }
        public string AKAMiddleName { get; set; }
        public Nullable<int> AKANameSuffixID { get; set; }
        public Nullable<int> AKATitleID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> RaceID { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<int> FederalRaceID { get; set; }
        public Nullable<int> FederalEthnicityID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> TimeOfBirth { get; set; }
        public Nullable<int> BirthOrderID { get; set; }
        public Nullable<int> BirthTypeID { get; set; }
        public Nullable<int> BirthStateID { get; set; }
        public string BirthCountyName { get; set; }
        public Nullable<int> BirthCountyID { get; set; }
        public Nullable<int> ResidentStateID { get; set; }
        public string ResidentCountyName { get; set; }
        public Nullable<int> ResidentCountyID { get; set; }
        public string BirthMotherLastName { get; set; }
        public string BirthMotherFirstName { get; set; }
        public string BirthMotherMiddleName { get; set; }
        public string MotherMaidenName { get; set; }
        public string MotherLastName { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherMiddleName { get; set; }
        public Nullable<int> MotherSuffixID { get; set; }
        public Nullable<System.DateTime> MotherDateOfBirth { get; set; }
        public Nullable<int> MotherGenderID { get; set; }
        public Nullable<int> MotherTitleID { get; set; }
        public Nullable<int> MotherPgmSourceID { get; set; }
        public Nullable<System.DateTime> MotherPgmEffectiveDate { get; set; }
        public string MotherSSN { get; set; }
        public Nullable<int> Relationship1ID { get; set; }
        public string FatherLastName { get; set; }
        public string FatherFirstName { get; set; }
        public string FatherMiddleName { get; set; }
        public Nullable<int> FatherSuffixID { get; set; }
        public Nullable<System.DateTime> FatherDateOfBirth { get; set; }
        public Nullable<int> FatherGenderID { get; set; }
        public Nullable<int> FatherTitleID { get; set; }
        public Nullable<int> FatherPgmSourceID { get; set; }
        public Nullable<System.DateTime> FatherPgmEffectiveDate { get; set; }
        public string FatherSSN { get; set; }
        public Nullable<int> Relationship2ID { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public Nullable<int> ResAddrPgmSourceID { get; set; }
        public Nullable<System.DateTime> ResAddrPgmEffectiveDate { get; set; }
        public string MobilePhone { get; set; }
        public string MailingAddress1 { get; set; }
        public string MailingAddress2 { get; set; }
        public string MailingCity { get; set; }
        public Nullable<int> MailingStateID { get; set; }
        public string MailingZip { get; set; }
        public Nullable<int> MailAddrPgmSourceID { get; set; }
        public Nullable<System.DateTime> MailAddrPgmEffectiveDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
