//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_Activity
    {
        public int ActivityID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime StatusDate { get; set; }
        public int StageStatusID { get; set; }
        public System.DateTime StageDate { get; set; }
        public int ActivityTypeID { get; set; }
        public Nullable<int> AuthorizationCodeID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<int> ActivityLevelID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> ResultTypeID { get; set; }
        public string UserResultCode { get; set; }
        public string UserResultCode2 { get; set; }
        public string UserResultValue { get; set; }
        public string UserResultValue2 { get; set; }
        public Nullable<int> UserResultSequence { get; set; }
        public string UserResultComment { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> NESTProviderID { get; set; }
        public string SourceProviderID { get; set; }
        public string SourceProvBusinessName { get; set; }
        public Nullable<int> SourceProviderTypeID { get; set; }
        public string SourceProvContactName { get; set; }
        public string SourceActivityID { get; set; }
        public Nullable<int> OriginalActivityID { get; set; }
        public string ResearchNumber { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string OriginUSERID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    }
}
