//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_VitalRecords_Deaths
    {
        public string ChildID { get; set; }
        public string VersionID { get; set; }
        public string EBC { get; set; }
        public string DOD { get; set; }
        public string DCert { get; set; }
    }
}
