//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_LastUpdated
    {
        public int ID { get; set; }
        public string Program { get; set; }
        public int PersonID { get; set; }
        public int RecordID { get; set; }
        public string RecordTable { get; set; }
        public string StatusChangeCode { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
    }
}
