//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEST_ValueConversion
    {
        public int vcID { get; set; }
        public string vcValue { get; set; }
        public string vcConvert { get; set; }
        public string vcNotes { get; set; }
    }
}
