//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeVisit
    {
        public int OfficeVisitID { get; set; }
        public long OfficeVisitGuidID { get; set; }
        public int ClientID { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime OfficeVisitDate { get; set; }
        public int SiteID { get; set; }
        public bool Pending { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ScreeningMethodBinID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DDScreeningMethodBin DDScreeningMethodBin { get; set; }
    }
}
