//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PercentFiscalYear
    {
        public int id { get; set; }
        public int FiscalYear { get; set; }
        public Nullable<System.DateTime> DateOfBillRun { get; set; }
        public Nullable<decimal> PercentOfFiscalYear { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    }
}
