//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string ProgramCode { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> SuffixID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<bool> Patient { get; set; }
        public string AKALastName { get; set; }
        public string AKAMiddleName { get; set; }
        public string AKAFirstName { get; set; }
        public System.DateTime DOB { get; set; }
        public string OriginCountry { get; set; }
        public Nullable<int> EthnicityHispanic { get; set; }
        public Nullable<int> LanguageSpokenID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<bool> Deceased { get; set; }
        public Nullable<System.DateTime> DateDeceased { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> EthnicityID { get; set; }
        public Nullable<System.DateTime> DateEnrollment { get; set; }
        public string MaidenName { get; set; }
        public Nullable<bool> EthnicityConfidential { get; set; }
        public Nullable<int> NoSSN { get; set; }
        public Nullable<bool> LimitedEnglish { get; set; }
        public Nullable<bool> ResponsibleParty { get; set; }
        public Nullable<int> InterpreterNeeded { get; set; }
        public Nullable<int> InactiveReasonID { get; set; }
        public Nullable<int> DeidentifiedID { get; set; }
    }
}
