//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRelationship
    {
        public int PRID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> RelatedPersonID { get; set; }
        public Nullable<int> RelationshipID { get; set; }
    }
}
