//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramScope
    {
        public int ScopeID { get; set; }
        public string Program { get; set; }
        public Nullable<int> SiteID { get; set; }
        public int ScopeIdentityID { get; set; }
        public string ScopeIdentityCode { get; set; }
        public string ScopeDescription { get; set; }
    }
}
