//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryReport
    {
        public int RegistryReportID { get; set; }
        public Nullable<int> ClinicalCycleID { get; set; }
        public Nullable<int> ScreeningID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<long> ScreeningGuidID { get; set; }
        public Nullable<long> OfficeVisitID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public string RegistryLinkStatusBinID { get; set; }
        public Nullable<System.DateTime> RegistryLinkStatusDate { get; set; }
        public Nullable<System.DateTime> RegistryDiagnosisDate { get; set; }
        public string RegistryHistTypeBinID { get; set; }
        public string RegistryBehaviorBinID { get; set; }
        public string RegistryPrimarySiteBinID { get; set; }
        public string RegistrySummaryStageBinID { get; set; }
        public string RegistryStageGroupBinID { get; set; }
        public string RegistryCsExtensionBinID { get; set; }
        public string RegistryCsLymphNodesBinID { get; set; }
        public string RegistryCsMetsBinID { get; set; }
        public string RegistryTumorSizeBinID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
