//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsDUMP
    {
        public int RequestID { get; set; }
        public string RequestDate { get; set; }
        public Nullable<System.DateTime> RequestDateActual { get; set; }
        public string RequestorID { get; set; }
        public string RequestTitle { get; set; }
        public int DivisionID { get; set; }
        public int RequestProgramID { get; set; }
        public int RequestTypeID { get; set; }
        public int PriorityID { get; set; }
        public int StateID { get; set; }
        public string RequestDesc { get; set; }
        public string UserID { get; set; }
        public string DeveloperNotes { get; set; }
        public string TestLog { get; set; }
        public Nullable<decimal> TimeToComplete { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BroadcastDate { get; set; }
        public bool TrainingIssue { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string RequestorNotes { get; set; }
        public string RequestedByID { get; set; }
    }
}
