//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public string RequestDate { get; set; }
        public Nullable<System.DateTime> RequestDateActual { get; set; }
        public string RequestorID { get; set; }
        public string RequestTitle { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> RequestProgramID { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string RequestDesc { get; set; }
        public string UserID { get; set; }
        public string DeveloperNotes { get; set; }
        public string TestLog { get; set; }
        public Nullable<decimal> TimeToComplete { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BroadcastDate { get; set; }
        public bool TrainingIssue { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string RequestorNotes { get; set; }
        public string RequestedByID { get; set; }
        public Nullable<bool> Overdue { get; set; }
        public Nullable<int> RequestModeID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<bool> OverdueWarning { get; set; }
        public Nullable<bool> RequestorViewed { get; set; }
        public Nullable<bool> AssigneeViewed { get; set; }
        public Nullable<int> Requestor { get; set; }
        public Nullable<bool> TestingMode { get; set; }
        public string Participants { get; set; }
        public Nullable<int> SubApplicationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public Nullable<int> RequestActionID { get; set; }
    }
}
