//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening
    {
        public int ScreeningID { get; set; }
        public Nullable<long> ScreeningGuidID { get; set; }
        public Nullable<long> OfficeVisitID { get; set; }
        public Nullable<int> ClinicalCycleID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<int> TobaccoUseBinID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public int ScreeningMethodBinID { get; set; }
        public Nullable<int> PrevScreenTestBinID { get; set; }
        public Nullable<int> HistPolypsBinID { get; set; }
        public Nullable<int> PolypPreCancerBinID { get; set; }
        public Nullable<int> PrevCancerBinID { get; set; }
        public Nullable<int> AgeDiagCancerBinID { get; set; }
        public Nullable<int> SuspectedGeneticDxBinID { get; set; }
        public Nullable<int> InflamBowelDisBinID { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public Nullable<System.DateTime> SchedDate { get; set; }
        public Nullable<int> CurrentStatusBinID { get; set; }
        public Nullable<int> RecScreenBinID { get; set; }
        public Nullable<int> ScreenReasonBinID { get; set; }
        public Nullable<int> KitDistMethodBinID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> BillingLevel { get; set; }
        public bool PersonalHistoryCancer { get; set; }
        public bool RelativeHistoryCancer { get; set; }
        public Nullable<int> PrevMamBinID { get; set; }
        public Nullable<int> PrevPapBinID { get; set; }
        public Nullable<int> CurrentMamReasonBinID { get; set; }
        public Nullable<int> CurrentPapReasonBinID { get; set; }
        public Nullable<int> HysterectomyStatusBinID { get; set; }
        public Nullable<System.DateTime> PrevCBEDate { get; set; }
        public Nullable<System.DateTime> PrevMamDate { get; set; }
        public Nullable<System.DateTime> PrevPapDate { get; set; }
        public Nullable<System.DateTime> MamRefDate { get; set; }
        public Nullable<System.DateTime> PapRefDate { get; set; }
        public Nullable<int> CancerTypeBinID { get; set; }
        public Nullable<System.DateTime> ScreenLockDate { get; set; }
        public Nullable<int> NoMamExplanationBinID { get; set; }
        public Nullable<int> NoPapExplanationBinID { get; set; }
        public Nullable<System.DateTime> BillingUpdatedDate { get; set; }
        public Nullable<int> BillingPaidBinID { get; set; }
        public Nullable<bool> FundedOfficeVisit { get; set; }
        public bool StateStaffOverride { get; set; }
        public Nullable<int> Symptom_SymptomID { get; set; }
        public Nullable<int> DDHistoryQuestionBin_HistoryQuestionBinID { get; set; }
        public Nullable<int> IrisScreenID { get; set; }
        public bool SuppressMDE { get; set; }
        public Nullable<bool> BillingHold { get; set; }
        public Nullable<int> DDHeightBinID { get; set; }
        public Nullable<int> DDWeightBinID { get; set; }
        public Nullable<int> DDWaistBinID { get; set; }
        public Nullable<int> DDHipBinID { get; set; }
        public Nullable<int> HeightBin_HeightBinID { get; set; }
        public Nullable<int> HipWaistBin_HipWaistBinID { get; set; }
        public Nullable<int> WeightBin_WeightBinID { get; set; }
        public Nullable<System.DateTime> HBReferralDate { get; set; }
        public Nullable<int> HBSessionTypeBinID { get; set; }
        public Nullable<int> HBSessionCompletionTypeBinID { get; set; }
        public Nullable<int> HBSessionBarrierTypeBinID { get; set; }
        public Nullable<int> FollowupCompletenessBinID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    
        public virtual DDCancerTypeBin DDCancerTypeBin { get; set; }
    }
}
