//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenComment
    {
        public int ScreenCommentID { get; set; }
        public int ScreeningID { get; set; }
        public int ClinicalCycleID { get; set; }
        public string ScreenCommentText { get; set; }
        public Nullable<bool> AdminOnly { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Screening Screening { get; set; }
    }
}
