//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenProcedure
    {
        public int ScreenProcedureID { get; set; }
        public Nullable<long> ScreeningProcGuidID { get; set; }
        public Nullable<int> ScreeningID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<long> ScreeningGuidID { get; set; }
        public Nullable<long> OfficeVisitID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<int> ClinicalCycleID { get; set; }
        public Nullable<int> ProcedureOutcomeBinID { get; set; }
        public Nullable<int> ProcedureMethodBinID { get; set; }
        public string ProcedureMethodOther { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public Nullable<int> ProcedureAge { get; set; }
        public Nullable<int> ProcedureResultBinID { get; set; }
        public Nullable<int> SubContractorID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> CecumReachedBinID { get; set; }
        public Nullable<int> QualityPrepBinID { get; set; }
        public Nullable<int> PatientGivenResultsBinID { get; set; }
        public Nullable<int> AdequateExamBinID { get; set; }
        public bool StateStaffOverride { get; set; }
        public bool Pathology { get; set; }
        public Nullable<int> PathPolypBinID { get; set; }
        public Nullable<int> PathHistBinID { get; set; }
        public Nullable<int> PathProviderBinID { get; set; }
        public string PathPolypsRemoved { get; set; }
        public string PathContainerCount { get; set; }
        public Nullable<bool> PathHighGradeDysplasia { get; set; }
        public string PathLargestAdenoma { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public bool Coverage { get; set; }
        public Nullable<int> ProcedureTypeBinID { get; set; }
        public Nullable<int> AdequacyBinID { get; set; }
        public Nullable<int> SpecimenTypeBinID { get; set; }
        public Nullable<System.DateTime> BillingUpdatedDate { get; set; }
        public Nullable<int> BillingPaidBinID { get; set; }
        public Nullable<int> FundingSourceBinID { get; set; }
        public bool AdminApproval { get; set; }
        public string OtherDxText { get; set; }
        public Nullable<bool> IsBethesda { get; set; }
        public Nullable<int> SystolicBinID1 { get; set; }
        public Nullable<int> DiastolicBinID1 { get; set; }
        public Nullable<int> SystolicBinID2 { get; set; }
        public Nullable<int> DiastolicBinID2 { get; set; }
        public Nullable<int> FastingStatusBinID { get; set; }
        public Nullable<int> TotalCholesterolBinID { get; set; }
        public Nullable<int> HDLCholesterolBinID { get; set; }
        public Nullable<int> LDLCholesterolBinID { get; set; }
        public Nullable<int> TriglyceridesBinID { get; set; }
        public Nullable<int> GlucoseBinID { get; set; }
        public Nullable<int> A1CPercentageBinID { get; set; }
        public Nullable<int> AlertBin_AlertBinID { get; set; }
        public Nullable<int> CholBin_TotalCholBinID { get; set; }
        public Nullable<int> DiastolicBin_DiastolicBinID { get; set; }
        public Nullable<int> SystolicBin_SystolicBinID { get; set; }
        public Nullable<int> TriglyceridesBin_TrigylceridesBinID { get; set; }
        public Nullable<int> AlertBinID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> WorkupStatusBinID { get; set; }
        public Nullable<int> WorkupResultBinID { get; set; }
        public Nullable<System.DateTime> WorkupStatusDate { get; set; }
        public Nullable<bool> MedicationCounselingProvided { get; set; }
        public Nullable<bool> BloodSample { get; set; }
        public Nullable<bool> TranslationProvided { get; set; }
        public Nullable<bool> BPPlus { get; set; }
    
        public virtual DDAdequacyBin DDAdequacyBin { get; set; }
        public virtual DDAdequateExamBin DDAdequateExamBin { get; set; }
        public virtual DDCecumReachedBin DDCecumReachedBin { get; set; }
        public virtual DDFundingSourceBin DDFundingSourceBin { get; set; }
        public virtual DDPathHistBin DDPathHistBin { get; set; }
        public virtual DDPathPolypBin DDPathPolypBin { get; set; }
        public virtual DDPatientGivenResultsBin DDPatientGivenResultsBin { get; set; }
        public virtual DDProcedureMethodBin DDProcedureMethodBin { get; set; }
        public virtual DDProcedureOutcomeBin DDProcedureOutcomeBin { get; set; }
        public virtual DDProcedureResultBin DDProcedureResultBin { get; set; }
        public virtual DDProcedureTypeBin DDProcedureTypeBin { get; set; }
        public virtual DDQualityPrepBin DDQualityPrepBin { get; set; }
        public virtual DDSpecimenTypeBin DDSpecimenTypeBin { get; set; }
        public virtual ScreenProcedure ScreenProcedure1 { get; set; }
        public virtual ScreenProcedure ScreenProcedure2 { get; set; }
    }
}
