//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public int ScreenID { get; set; }
        public string ScreenName { get; set; }
        public int ScreenOrder { get; set; }
        public Nullable<bool> QuickView { get; set; }
        public Nullable<bool> Grid { get; set; }
        public Nullable<bool> Tree { get; set; }
        public Nullable<bool> DataEntry { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
