//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDissolutionData
    {
        public System.Guid ID { get; set; }
        public Nullable<int> DissolutionID { get; set; }
        public string PetitionerFirstName { get; set; }
        public string PetitionerMiddleName { get; set; }
        public string PetitionerLastName { get; set; }
        public string RespondentFirstName { get; set; }
        public string RespondentMiddleName { get; set; }
        public string RespondentLastName { get; set; }
        public Nullable<System.DateTime> DecreeDate { get; set; }
        public Nullable<int> DecreeYear { get; set; }
        public Nullable<int> DecreeMonth { get; set; }
        public Nullable<int> DecreeDay { get; set; }
        public string DecreeCode { get; set; }
        public Nullable<int> CountyCode { get; set; }
        public Nullable<int> DocketNumber { get; set; }
        public Nullable<int> Void { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastCorrectionDate { get; set; }
        public string CorrectionNote { get; set; }
        public string DataEntryCorrection { get; set; }
        public Nullable<System.DateTime> DateRecordSaved { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<byte> FlagRecord { get; set; }
        public string FlagNotes { get; set; }
    }
}
