//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarriageFileUploadData
    {
        public int ID { get; set; }
        public string MarriageID { get; set; }
        public string RecordType { get; set; }
        public string Record { get; set; }
        public string RecordYear { get; set; }
        public string StateFileNumber { get; set; }
        public string RecordConstant { get; set; }
        public string County { get; set; }
        public string CountyFileNumber { get; set; }
        public string PartyOneFN { get; set; }
        public string PartyOneMN { get; set; }
        public string PartyOneLN { get; set; }
        public string PartyOneDOB { get; set; }
        public string PartyOneDOBDay { get; set; }
        public string PartyOneDOBMonth { get; set; }
        public string PartyOneDOBYear { get; set; }
        public string PartyOneMaritalStatus { get; set; }
        public string PartyOneDissolutionDate { get; set; }
        public string PartyOnePriorDissolutionMonth { get; set; }
        public string PartyOnePriorDissolutionDay { get; set; }
        public string PartyOnePriorDissolutionYear { get; set; }
        public string PartyTwoFN { get; set; }
        public string PartyTwoMN { get; set; }
        public string PartyTwoLn { get; set; }
        public string PartyTwoDOB { get; set; }
        public string PartyTwoDOBDay { get; set; }
        public string PartyTwoDOBMonth { get; set; }
        public string PartyTwoDOBYear { get; set; }
        public string PartyTwoMaritalStatus { get; set; }
        public string PartyTwoPriorDissolutionDate { get; set; }
        public string PartyTwoPriorDissolutionMonth { get; set; }
        public string PartyTwoPriorDissolutionDay { get; set; }
        public string PartyTwoPriorDissolutionYear { get; set; }
        public string CeremonyType { get; set; }
        public string CeremonyDate { get; set; }
        public string CeremonyDay { get; set; }
        public string CeremonyMonth { get; set; }
        public string CeremonyYear { get; set; }
        public string PartiesRelated { get; set; }
        public string PartyOneResidenceState { get; set; }
        public string PartyOneBirthState { get; set; }
        public string PartyTwoResidenceState { get; set; }
        public string PartyTwoBirthState { get; set; }
        public string PartyOneSex { get; set; }
        public string PartyTwoSex { get; set; }
        public string VoidID { get; set; }
        public string VoidInd { get; set; }
        public string Void { get; set; }
        public string VoidDate { get; set; }
        public string CreateDt { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string LastCorrectionDate { get; set; }
        public string LastCorrectionYear { get; set; }
        public string LastCorrectionMonth { get; set; }
        public string LastCorrectionDay { get; set; }
        public string CorrectionNote { get; set; }
        public string FirstDateofCorrection { get; set; }
        public string DataEntryCorrection { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RowStatus { get; set; }
        public string ErrMsg { get; set; }
    }
}
