//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarriageSearchLog
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string SearchType { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
