//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAccount
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string Agency { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<byte> ChargeMember { get; set; }
        public Nullable<System.DateTime> MemberExpDate { get; set; }
        public Nullable<byte> AccountLocked { get; set; }
        public string AgencyName { get; set; }
        public Nullable<int> AgencyType { get; set; }
        public string AgencyTypeOther { get; set; }
        public Nullable<int> AgencyFunction { get; set; }
        public string AgencyFunctionOther { get; set; }
        public string AgencyFunctionCountyName { get; set; }
        public string AgencyFunctionCountyCode { get; set; }
        public string AgencyLocation { get; set; }
        public string SupFirstName { get; set; }
        public string SupLastName { get; set; }
        public string SupEmail { get; set; }
        public string AccessRequestReason { get; set; }
        public Nullable<byte> SupApproval { get; set; }
    }
}
