//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCountyAccess
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string CountyName { get; set; }
        public string CountyCode { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    }
}
