//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOption
    {
        public int UserOptionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string ToolbarCode { get; set; }
        public string QuickViewCode { get; set; }
        public string Theme { get; set; }
        public Nullable<bool> CalendarEventDisplay { get; set; }
        public Nullable<System.DateTime> StartTimeCalendar { get; set; }
        public Nullable<System.DateTime> EndTimeCalendar { get; set; }
        public Nullable<int> NotificationViewID { get; set; }
        public Nullable<int> DataEntryID { get; set; }
    }
}
