//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIPAddress
    {
        public int LogActivityID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string InitialLoginIP { get; set; }
        public string SecondLoginIP { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
