//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTest
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Street_Address_1 { get; set; }
        public string Street_ADdress_2 { get; set; }
        public string City { get; set; }
        public string State_Code { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public int UPD { get; set; }
        public string RPType { get; set; }
    }
}
