//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMDEErrorField
    {
        public int ID { get; set; }
        public string Error { get; set; }
        public string WMDEField { get; set; }
        public string ErrorDescription { get; set; }
        public string UserExp { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
