//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMDE_Errors_2
    {
        public string ID { get; set; }
        public string ClientID { get; set; }
        public string SiteID { get; set; }
        public string BPDate { get; set; }
        public string RowNumber { get; set; }
        public string FieldName { get; set; }
        public string ErrorType { get; set; }
        public string Error { get; set; }
        public string Description { get; set; }
        public string BPDate1 { get; set; }
    }
}
